---
- name: Generate Debug
  template:
    src: "spring_config.j2"
    dest: "debug_configs/{{ inventory_hostname}}_spring_config.txt"

- name: Generate Segment Routing Configuration
  junos_config:
    lines: "{{ lookup('template', 'spring_config.j2').split('\n') }}"
    comment: "Configured SPRING"
